
title = "–ê—Ä–∞–º–∞ –ê–Ω–Ω–∞"
author = "Arama Anna"
#copyright = "2020-2021"
description = "Arama Anna üèä‚Äç‚ôÄÔ∏èüö¥‚Äç‚ôÄÔ∏èüèÉüèΩ"
profilePicture = "images/profile.jpg"
keywords = "–ê—Ä–∞–º–∞, Arama, —Ç—Ä–µ–Ω–µ—Ä, –ø–µ—Ä—Å–æ–Ω–∞–ª—å–Ω—ã–π —Ç—Ä–µ–Ω–µ—Ä, —Ç—Ä–∏–∞—Ç–ª–µ—Ç"
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
#images = ["images/site-feature-tumba1.png"]
images=["images/profile.jpg"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
#contactFormReCaptcha = "your-site-key-here"
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "02.01.2006"
indexDateFormat = "02.01.2006"
listDateFormat = "02.01.2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"
relatedPosts =false
numberOfRelatedPosts = 2
# disableTitleCapitalization = true
disableLanguageSwitchingButton = true



reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'
disableThemeSwitcher = true
toc = true

# hidesidebar = true

[simpleAnalytics]
enable = true
# customurl = "https://analytics.example.com"

[plausibleAnalytics]
# domain = "example.com"
# serverURL = "https://analytics.example.com"

[umami]
# serverURL = "example.com"
# id = "94db1cb1-74f4-4a40-ad6c-962362670409"
# trackerScriptName = "mycustomscriptname.js"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fa-brands' when brand icons, use 'fas' when standard solid icons.

[[socialIcons]]
icon = "fa-brands fa-telegram"
title = "Telegram"
url = "https://t.me/anna_arama"

[[socialIcons]]
icon = "fa-brands fa-instagram"
title = "instagram"
url = "https://www.instagram.com/anna_arama"

[[socialIcons]]
icon = "fa-solid fa-envelope"
title = "e-mail"
url = "mailto:anna@arama.pro"

[[socialIcons]]
icon = "fa-brands fa-strava"
title = "strava"
url = "https://www.strava.com/athletes/99577195"

[mermaid]
enable = false

